"""
Attention Weight Visualization for Attentive Probes
====================================================

This script extracts and visualizes the spatial attention weights generated by the
attentive probe (cross-attention layer). The attention weights show which regions
of the video the probe prioritizes when making predictions.

Key steps:
1. Load the pretrained encoder and attentive probe checkpoint
2. Extract 1D spatial attention weights via forward hooks
3. Reshape to 3D spatiotemporal grid (T, H, W)
4. Upsample to original video resolution
5. Create heatmap overlays for each frame
6. Save as MP4 video or sequence of PNG frames

Requirements:
- torch
- opencv-python (cv2)
- imageio (for video writing)
- numpy
- matplotlib
- yaml
"""

import os
import sys
from pathlib import Path
from typing import Tuple, List, Optional
import logging
import argparse

import numpy as np
import torch
import torch.nn.functional as F
import cv2
import matplotlib.pyplot as plt
import imageio

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# Import model components
from evals.video_classification_frozen.eval import make_dataloader
from evals.video_classification_frozen.models import init_module
from src.models.attentive_pooler import AttentiveClassifier
from src.utils.checkpoint_loader import robust_checkpoint_loader

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

DEFAULT_NORMALIZATION = ((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))


class AttentionWeightExtractor:
    """Extract attention weights from AttentivePooler via forward hooks."""

    def __init__(
        self,
        device: torch.device,
        aggregation: str = "entropy_weighted",
        debias_uniform: bool = True,
    ):
        self.device = device
        self.aggregation = aggregation
        self.debias_uniform = debias_uniform
        self.attention_weights = None
        self.attention_weights_per_head = None
        self.hook_handle = None

    def _aggregate_heads(self, attn: torch.Tensor) -> torch.Tensor:
        """Aggregate per-head attention [B, h, Q, N] to [B, Q, N] with explicit strategy."""
        if self.aggregation == "mean":
            aggregated = attn.mean(dim=1)
        elif self.aggregation == "max":
            aggregated, _ = attn.max(dim=1)
        elif self.aggregation == "entropy_weighted":
            n_tokens = attn.shape[-1]
            eps = torch.finfo(attn.dtype).eps
            entropy = -(attn.clamp_min(eps) * attn.clamp_min(eps).log()).sum(dim=-1)  # [B, h, Q]
            entropy_norm = entropy / np.log(max(n_tokens, 2))
            sharpness = (1.0 - entropy_norm).clamp(min=0.0)
            weights = sharpness / (sharpness.sum(dim=1, keepdim=True) + 1e-8)
            aggregated = (attn * weights.unsqueeze(-1)).sum(dim=1)
        else:
            raise ValueError(f"Unknown aggregation mode '{self.aggregation}'. Use mean|max|entropy_weighted.")

        if self.debias_uniform:
            uniform_floor = 1.0 / aggregated.shape[-1]
            aggregated = (aggregated - uniform_floor).clamp_min(0.0)

        return aggregated

    def hook_fn(self, module: torch.nn.Module, input: Tuple, output: torch.Tensor):
        """
        Forward hook to capture attention weights from CrossAttention.
        """
        q_input, x_input = input[0], input[1]
        attn_mask = input[2] if len(input) > 2 else None

        B, Q, C = q_input.shape
        num_heads = module.num_heads

        # 1. Exact projections mirroring your CrossAttention.forward
        q = module.q(q_input).reshape(B, Q, num_heads, C // num_heads).permute(0, 2, 1, 3)

        B, N, C = x_input.shape
        kv = module.kv(x_input).reshape(B, N, 2, num_heads, C // num_heads).permute(2, 0, 3, 1, 4)
        k = kv[0]  # [B, h, N, d]

        # We don't need v for attention maps

        # 2. Compute attention weights using the module's exact scale
        scale = module.scale
        attn = (q @ k.transpose(-2, -1)) * scale  # [B, h, Q, N]

        # Respect masking exactly like CrossAttention.forward when provided.
        if attn_mask is not None:
            additive = attn_mask[:, None, None, :].to(attn.dtype) * torch.finfo(attn.dtype).min
            attn = attn + additive

        # Apply softmax to get probability distributions
        attn = attn.softmax(dim=-1)  # [B, h, Q, N]

        # Keep per-head attention for diagnostics, and aggregate with explicit strategy.
        self.attention_weights_per_head = attn.detach().cpu()
        attn = self._aggregate_heads(attn)

        # Store on CPU to avoid GPU memory leaks
        self.attention_weights = attn.detach().cpu()

    def register_hook(self, cross_attention_module: torch.nn.Module) -> None:
        self.hook_handle = cross_attention_module.register_forward_hook(self.hook_fn)
        logger.info("Attention weight hook registered")

    def remove_hook(self) -> None:
        if self.hook_handle is not None:
            self.hook_handle.remove()
            logger.info("Attention weight hook removed")

    def get_weights(self) -> Optional[torch.Tensor]:
        return self.attention_weights

    def get_weights_per_head(self) -> Optional[torch.Tensor]:
        return self.attention_weights_per_head


def reshape_attention_to_grid(
    attention_weights: torch.Tensor,
    T: int,
    H: int,
    W: int,
) -> torch.Tensor:
    """
    Reshape 1D attention weights to 3D spatiotemporal grid.

    Args:
        attention_weights: tensor of shape [B, Q, N] where N = T*H*W
        T: number of frames
        H: spatial height in patches
        W: spatial width in patches

    Returns:
        tensor of shape [B, 1, T, H, W] (adds channel dim for compatibility)
    """
    B, Q, N = attention_weights.shape
    assert Q == 1, f"Expected single query token, got {Q}"
    assert N == T * H * W, f"Token count {N} doesn't match T*H*W={T}*{H}*{W}={T*H*W}"

    # Reshape: [B, 1, N] -> [B, 1, T, H, W]
    grid = attention_weights.reshape(B, 1, T, H, W)
    logger.debug(f"Reshaped attention to grid: {grid.shape}")
    return grid


def upsample_attention_to_video_resolution(
    attention_grid: torch.Tensor,
    target_shape: Tuple[int, int, int],
) -> torch.Tensor:
    """
    Upsample low-resolution attention grid to original video resolution.

    Args:
        attention_grid: tensor of shape [B, C, T, H, W]
        target_shape: (T_tgt, H_tgt, W_tgt) target resolution

    Returns:
        tensor of shape [B, C, T_tgt, H_tgt, W_tgt]
    """
    T_tgt, H_tgt, W_tgt = target_shape

    B, C, T_src, H_src, W_src = attention_grid.shape

    # Spatial-only interpolation avoids inventing intermediate temporal attention mass.
    attention_spatial = attention_grid.permute(0, 2, 1, 3, 4).reshape(B * T_src, C, H_src, W_src)
    attention_spatial = F.interpolate(attention_spatial, size=(H_tgt, W_tgt), mode='bilinear', align_corners=False)
    attention_spatial = attention_spatial.reshape(B, T_src, C, H_tgt, W_tgt).permute(0, 2, 1, 3, 4)

    # Temporal alignment is discrete; use repeat/average only when ratio is integer.
    if T_src == T_tgt:
        attention_up = attention_spatial
    elif T_tgt % T_src == 0:
        repeat_factor = T_tgt // T_src
        attention_up = attention_spatial.repeat_interleave(repeat_factor, dim=2)
    elif T_src % T_tgt == 0:
        pool_factor = T_src // T_tgt
        attention_up = attention_spatial.reshape(B, C, T_tgt, pool_factor, H_tgt, W_tgt).mean(dim=3)
    else:
        raise ValueError(
            f"Temporal alignment is ambiguous: attention has T={T_src}, frames have T={T_tgt}. "
            "Set data loading so these match or use integer-ratio clip/view settings."
        )

    logger.debug(f"Upsampled attention to video resolution: {attention_up.shape}")
    return attention_up


def normalize_attention(
    attention_tensor: torch.Tensor,
    low_quantile: float = 0.01,
    high_quantile: float = 0.99,
) -> torch.Tensor:
    """
    Normalize attention weights to [0, 1] using robust percentile clipping.
    """
    # Flatten the tensor to calculate quantiles globally across the video
    flat_attn = attention_tensor.float().view(-1)

    if not (0.0 <= low_quantile < high_quantile <= 1.0):
        raise ValueError(f"Invalid quantiles: low={low_quantile}, high={high_quantile}")

    min_val = torch.quantile(flat_attn, low_quantile)
    max_val = torch.quantile(flat_attn, high_quantile)

    if max_val <= min_val:
        logger.warning("Attention has uniform values; normalization will produce zeros")
        return torch.zeros_like(attention_tensor)

    # Normalize and clamp to ensure values above the 99th percentile stop at 1.0
    normalized = torch.clamp((attention_tensor - min_val) / (max_val - min_val), 0.0, 1.0)

    logger.debug(f"Normalized attention range: [{normalized.min():.4f}, {normalized.max():.4f}]")
    return normalized


def attention_to_heatmap(
    attention_frame: np.ndarray,
    colormap: int = cv2.COLORMAP_JET,
    vmin: float = 0.0,  # NEW: minimum value for colormap scaling
    vmax: float = 1.0,
) -> np.ndarray:
    """
    Convert single-channel attention frame to RGB heatmap, rescaling
    the active range [vmin, vmax] to span the full colormap.
    """
    # Protect against division by zero if vmin == vmax
    if vmax <= vmin:
        rescaled = np.zeros_like(attention_frame)
    else:
        # Stretch the [vmin, vmax] range to [0.0, 1.0]
        rescaled = (attention_frame - vmin) / (vmax - vmin)

    # Clip values outside the bounds to [0, 1] and convert to uint8
    attention_uint8 = (np.clip(rescaled, 0.0, 1.0) * 255).astype(np.uint8)

    # Apply colormap (returns BGR)
    heatmap_bgr = cv2.applyColorMap(attention_uint8, colormap)

    # Convert BGR to RGB
    heatmap_rgb = cv2.cvtColor(heatmap_bgr, cv2.COLOR_BGR2RGB)
    return heatmap_rgb


def blend_heatmap_with_frame(
    frame: np.ndarray,
    heatmap: np.ndarray,
    attention_frame: Optional[np.ndarray] = None,
    alpha: float = 0.5,
    threshold: float = 0.0,
) -> np.ndarray:
    """
    Blend attention heatmap over video frame using an optional threshold mask.
    """
    frame_float = frame.astype(np.float32) / 255.0
    heatmap_float = heatmap.astype(np.float32) / 255.0

    # If a threshold is set, create a spatial alpha mask
    if attention_frame is not None and threshold > 0.0:
        # mask is `alpha` where attention >= threshold, and `0.0` otherwise
        dynamic_alpha = np.where(attention_frame >= threshold, alpha, 0.0).astype(np.float32)
        # Add channel dimension [H, W, 1] so it broadcasts with RGB arrays
        dynamic_alpha = np.expand_dims(dynamic_alpha, axis=-1)
    else:
        # Fallback to standard global blending
        dynamic_alpha = alpha

    # Blend: output = (1 - alpha) * frame + alpha * heatmap
    blended = (1.0 - dynamic_alpha) * frame_float + dynamic_alpha * heatmap_float

    blended_uint8 = np.clip(blended * 255.0, 0, 255).astype(np.uint8)
    return blended_uint8


def denormalize_frame(
    frame_normalized: torch.Tensor,
    mean: Tuple[float, float, float] = (0.485, 0.456, 0.406),
    std: Tuple[float, float, float] = (0.229, 0.224, 0.225),
) -> np.ndarray:
    """
    Denormalize a frame tensor (after model normalization) back to [0, 255] uint8.

    Args:
        frame_normalized: tensor [C, H, W] with values normalized by mean/std
        mean: normalization mean per channel
        std: normalization std per channel

    Returns:
        denormalized frame [H, W, 3] uint8
    """
    frame = frame_normalized.detach().cpu()

    # Accept a leading singleton batch dimension, but reject full clip tensors.
    if frame.ndim == 4:
        if frame.shape[0] == 1:
            frame = frame.squeeze(0)
        else:
            raise ValueError(
                f"denormalize_frame expects a single frame tensor, got shape {tuple(frame.shape)}. "
                "Select one temporal frame before denormalizing."
            )

    frame_np = frame.numpy()

    # Convert to HWC if needed.
    if frame_np.ndim == 2:
        frame_np = frame_np[..., None]
    elif frame_np.ndim == 3:
        if frame_np.shape[0] in (1, 3) and frame_np.shape[-1] not in (1, 3):
            frame_np = np.transpose(frame_np, (1, 2, 0))
    else:
        raise ValueError(f"Unexpected frame shape {frame_np.shape}; expected 2D or 3D image tensor.")

    if frame_np.shape[-1] == 1:
        frame_np = np.repeat(frame_np, 3, axis=-1)
    elif frame_np.shape[-1] != 3:
        raise ValueError(f"denormalize_frame expected 1 or 3 channels, got shape {frame_np.shape}.")

    # Denormalize
    mean_arr = np.array(mean, dtype=np.float32)
    std_arr = np.array(std, dtype=np.float32)
    frame_denorm = frame_np * std_arr + mean_arr

    # Clip to [0, 1] and convert to uint8
    frame_denorm = np.clip(frame_denorm, 0, 1)
    frame_uint8 = (frame_denorm * 255).astype(np.uint8)

    return frame_uint8


def create_attention_video(
    video_frames: List[np.ndarray],
    attention_sequence: torch.Tensor,
    output_path: str,
    fps: int = 10,
    alpha: float = 0.5,
    frame_format: str = 'RGB',
    threshold: float = 0.0,
) -> None:
    """
    Create and save video with attention heatmap overlay.

    Args:
        video_frames: list of frames (H, W, 3) uint8, one per time step
        attention_sequence: tensor [T, H, W] with normalized attention weights
        output_path: path to save output video (MP4 or GIF)
        fps: frames per second
        alpha: heatmap blending coefficient
        frame_format: 'RGB' or 'BGR'
    """
    T = len(video_frames)
    assert attention_sequence.shape[0] == T, f"Frame count mismatch: {T} vs {attention_sequence.shape[0]}"

    H, W = video_frames[0].shape[:2]
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    logger.info(f"Creating attention video: {T} frames at {fps} fps")
    logger.info(f"Output: {output_path}")

    blended_frames = []

    for t in range(T):
        frame = video_frames[t]
        attention_frame = attention_sequence[t].detach().cpu().numpy()  # [H, W]
        heatmap = attention_to_heatmap(attention_frame, vmin=threshold)

        # Pass the attention_frame and threshold to the blender
        blended = blend_heatmap_with_frame(
            frame,
            heatmap,
            attention_frame=attention_frame,
            alpha=alpha,
            threshold=threshold
        )
        blended_frames.append(blended)

    # Save video
    if output_path.suffix.lower() in ['.mp4', '.avi']:
        # Use imageio to write MP4
        logger.info(f"Writing MP4 video to {output_path}")
        imageio.mimsave(str(output_path), blended_frames, fps=fps, format="FFMPEG")
    elif output_path.suffix.lower() == '.gif':
        # Write GIF
        logger.info(f"Writing GIF to {output_path}")
        imageio.mimsave(str(output_path), blended_frames, fps=fps)
    else:
        # Default to MP4
        output_mp4 = output_path.with_suffix('.mp4')
        logger.info(f"Unknown format; writing MP4 to {output_mp4}")
        imageio.mimsave(str(output_mp4), blended_frames, fps=fps)

    logger.info(f"✓ Attention video saved: {output_path}")


def extract_video_frames_from_sample(
    sample_clips: List[torch.Tensor],
    mean: Tuple[float, float, float],
    std: Tuple[float, float, float],
) -> List[np.ndarray]:
    """
    Extract and denormalize all frames from one sample.

    The eval dataloader typically returns each sample as a list of clip/view tensors.
    Each clip can be shaped like [B, C, T, H, W], [C, T, H, W], [T, C, H, W], or [T, H, W, C].
    This helper converts each temporal slice back to [H, W, 3] uint8 frames.
    """
    video_frames: List[np.ndarray] = []

    for clip_idx, clip_tensor in enumerate(sample_clips):
        clip_tensor = clip_tensor.detach().cpu()

        # Remove leading batch dimension if present (shape [1, C, T, H, W] -> [C, T, H, W])
        if clip_tensor.ndim == 5:
            if clip_tensor.shape[0] == 1:
                clip_tensor = clip_tensor.squeeze(0)
            else:
                raise ValueError(
                    f"Unexpected batch size {clip_tensor.shape[0]} at clip/view index {clip_idx}. "
                    f"Expected batch size 1 for single sample. Shape: {tuple(clip_tensor.shape)}"
                )

        if clip_tensor.ndim == 4:
            # Common eval layout: [C, T, H, W]
            if clip_tensor.shape[0] in (1, 3):
                temporal_len = clip_tensor.shape[1]
                frames = [clip_tensor[:, t] for t in range(temporal_len)]
            # Fallback layouts: [T, C, H, W] or [T, H, W, C]
            elif clip_tensor.shape[1] in (1, 3):
                temporal_len = clip_tensor.shape[0]
                frames = [clip_tensor[t] for t in range(temporal_len)]
            elif clip_tensor.shape[-1] in (1, 3):
                temporal_len = clip_tensor.shape[0]
                frames = [clip_tensor[t] for t in range(temporal_len)]
            else:
                raise ValueError(
                    f"Unsupported clip tensor shape {tuple(clip_tensor.shape)} at clip/view index {clip_idx}."
                )
        elif clip_tensor.ndim == 3:
            frames = [clip_tensor]
        else:
            raise ValueError(
                f"Unsupported clip tensor ndim={clip_tensor.ndim} with shape {tuple(clip_tensor.shape)} at clip/view index {clip_idx}."
            )

        for frame_tensor in frames:
            video_frames.append(denormalize_frame(frame_tensor, mean, std))

    return video_frames


def load_encoder_and_classifier(
    config_dict: dict,
    probe_checkpoint_path: str,
    device: torch.device,
        head_idx: int | None = None,
) -> Tuple[torch.nn.Module, AttentiveClassifier, int]:
    """
    Load pretrained encoder and attentive classifier.

    Args:
        config_dict: evaluation configuration dictionary
        probe_checkpoint_path: path to probe checkpoint
        device: torch device

    Returns:
        encoder, classifier, best_head_idx
    """
    args_pretrain = config_dict.get("model_kwargs")
    checkpoint = args_pretrain.get("checkpoint")
    module_name = args_pretrain.get("module_name")
    args_model = args_pretrain.get("pretrain_kwargs")
    args_wrapper = args_pretrain.get("wrapper_kwargs")

    args_exp = config_dict.get("experiment")
    args_classifier = args_exp.get("classifier")
    args_data = args_exp.get("data")

    # Load encoder
    encoder = init_module(
        module_name=module_name,
        frames_per_clip=args_data.get("frames_per_clip", 16),
        resolution=args_data.get("resolution", 224),
        checkpoint=checkpoint,
        model_kwargs=args_model,
        wrapper_kwargs=args_wrapper,
        device=device,
    )

    logger.info(f"Loaded encoder: {module_name}")

    # Load probe checkpoint
    if not os.path.exists(probe_checkpoint_path):
        raise FileNotFoundError(f"Probe checkpoint not found: {probe_checkpoint_path}")

    checkpoint_dict = robust_checkpoint_loader(probe_checkpoint_path, map_location=device)

    # Determine best head
    best_head_idx = 0
    if "best_val_acc_per_head" in checkpoint_dict:
        best_val_accs = checkpoint_dict["best_val_acc_per_head"]
        best_head_idx = int(np.argmax(best_val_accs))
        logger.info(f"Found best head: {best_head_idx} with val acc {best_val_accs[best_head_idx]:.4f}")

    if head_idx is not None:
        best_head_idx = head_idx
        logger.info(f"Head idx overwritten by commandline, using head idx: {head_idx}")

    # Create classifier
    num_classes = args_data.get("num_classes")
    num_probe_blocks = args_classifier.get("num_probe_blocks", 1)
    num_heads = args_classifier.get("num_heads", 16)

    classifier = AttentiveClassifier(
        embed_dim=encoder.embed_dim,
        num_heads=num_heads,
        depth=num_probe_blocks,
        num_classes=num_classes,
        use_activation_checkpointing=True,
    ).to(device)

    classifier.load_state_dict(checkpoint_dict["classifiers"][best_head_idx])
    logger.info(f"Loaded classifier from checkpoint")

    return encoder, classifier, best_head_idx


def extract_spatial_dimensions(encoder: torch.nn.Module, encoder_output: torch.Tensor, nominal_num_frames: int) -> Tuple[int, int, int]:
    """
    Infer spatial patch grid dimensions from encoder output, using encoder metadata when
    available. This is robust to wrappers that concatenate multiple clips/views which
    increase the effective temporal length.

    Args:
        encoder: the encoder module returned by init_module (may be a wrapper)
        encoder_output: list of clip embeddings or single tensor [B, N, D]
        nominal_num_frames: nominal frames_per_clip from the config (per-clip)

    Returns:
        (H_patch, W_patch, T_effective) where T_effective is the number of temporal
        indices represented in the encoder output (may be > nominal_num_frames if
        the encoder concatenates clips/views).
    """
    # Resolve token tensor
    if isinstance(encoder_output, list):
        tokens = encoder_output[0]  # [B, N, D]
    else:
        tokens = encoder_output

    B, N, D = tokens.shape

    # Try to read spatial grid from encoder model metadata (works for VisionTransformer and wrappers)
    model_for_meta = getattr(encoder, "model", encoder)
    try:
        patch_size = getattr(model_for_meta, "patch_size")
        img_h = getattr(model_for_meta, "img_height")
        img_w = getattr(model_for_meta, "img_width")
        H_patch = img_h // patch_size
        W_patch = img_w // patch_size
        spatial_tokens_per_frame = H_patch * W_patch
    except Exception:
        # Fallback: infer spatial tokens by dividing total tokens by nominal frames
        T_nom = nominal_num_frames
        spatial_tokens_per_frame = N // T_nom
        # Attempt square approximation
        H_patch = W_patch = int(np.sqrt(spatial_tokens_per_frame))

    # Compute effective temporal length represented in tokens
    if spatial_tokens_per_frame > 0:
        T_effective = N // spatial_tokens_per_frame
    else:
        T_effective = nominal_num_frames

    if H_patch * W_patch != spatial_tokens_per_frame:
        logger.warning(
            f"Non-square or mismatched spatial grid detected: {N} tokens / {T_effective} frames = {spatial_tokens_per_frame} spatial tokens. "
            f"Assuming {H_patch} x {W_patch} grid (may be incorrect)."
        )

    logger.info(f"Inferred spatial grid: {H_patch} x {W_patch} (T_effective={T_effective}, nominal={nominal_num_frames})")
    return H_patch, W_patch, T_effective


def visualize_attention(
    eval_config_path: str,
    probe_checkpoint_path: str,
    test_data_path: Optional[str] = None,
    output_dir: str = "notebooks/attention_visualizations",
    sample_index: int = 0,
    gpu_id: int = 0,
    heatmap_alpha: float = 0.5,
    fps: int = 10,
    head_idx = None,
    threshold: float = 0.0,
    head_aggregation: str = "entropy_weighted",
    debias_uniform: bool = True,
    norm_low_q: float = 0.01,
    norm_high_q: float = 0.99,
) -> None:
    """
    Main pipeline to extract and visualize attention weights.

    Args:
        eval_config_path: path to evaluation config YAML
        probe_checkpoint_path: path to probe checkpoint
        test_data_path: path to test data (optional; uses config default if not provided)
        output_dir: directory to save visualizations
        sample_index: which sample to visualize
        gpu_id: GPU ID to use
        heatmap_alpha: blending coefficient for heatmap
        fps: video frame rate
    """
    # Setup device
    device = torch.device(f"cuda:{gpu_id}" if torch.cuda.is_available() else "cpu")
    os.environ['CUDA_VISIBLE_DEVICES'] = str(gpu_id)
    logger.info(f"Using device: {device}")

    # Load config
    import yaml
    with open(eval_config_path, 'r') as f:
        eval_config = yaml.safe_load(f)

    # Load models
    logger.info("Loading encoder and classifier...")
    encoder, classifier, _ = load_encoder_and_classifier(
        eval_config,
        probe_checkpoint_path,
        device,
        head_idx
    )

    encoder.eval()
    classifier.eval()

    # Setup attention hook
    logger.info("Setting up attention weight extraction...")
    extractor = AttentionWeightExtractor(
        device,
        aggregation=head_aggregation,
        debias_uniform=debias_uniform,
    )

    # The classifier contains a pooler which contains the CrossAttention
    cross_attn = classifier.pooler.cross_attention_block.xattn
    extractor.register_hook(cross_attn)

    # Load test data
    args_data = eval_config.get("experiment").get("data")
    test_data_path = test_data_path or args_data.get("dataset_val")

    logger.info(f"Loading test data from {test_data_path}")
    test_loader, _ = make_dataloader(
        dataset_type=args_data.get("dataset_type", "VideoDataset"),
        root_path=[test_data_path],
        img_size=args_data.get("resolution", 224),
        frames_per_clip=args_data.get("frames_per_clip", 16),
        frame_step=args_data.get("frame_step", 4),
        eval_duration=args_data.get("clip_duration", None),
        num_segments=args_data.get("num_segments", 1),
        num_views_per_segment=args_data.get("num_views_per_segment", 1),
        allow_segment_overlap=True,
        batch_size=1,
        world_size=1,
        rank=0,
        training=False,
        num_workers=0,
        normalization=DEFAULT_NORMALIZATION,
    )

    # Get sample
    logger.info(f"Extracting sample {sample_index}...")
    sample_found = False
    batch_idx = -1
    for batch_idx, batch in enumerate(test_loader):
        if batch_idx != sample_index:
            continue

        sample_found = True
        clips = [[dij.to(device) for dij in di] for di in batch[0]]
        clip_indices = [d.to(device) for d in batch[2]]
        sample_clips = clips[0]

        logger.info(
            f"Sample shape: {len(clips)} batch item(s), {len(sample_clips)} clip/view tensor(s) in the selected sample"
        )

        # Forward pass
        logger.info("Running forward pass...")
        with torch.no_grad():
            encoder_output = encoder(clips, clip_indices)

        # Get encoder output shape to infer spatial patch grid and effective temporal length
        H_patch, W_patch, T_effective = extract_spatial_dimensions(
            encoder, encoder_output, args_data.get("frames_per_clip", 16)
        )

        # Get first clip's features (they're all the same if num_segments=1)
        if isinstance(encoder_output, list):
            features = encoder_output[0]  # [B, N, D]
        else:
            features = encoder_output  # [B, N, D]

        # Forward through classifier to trigger attention hook
        logger.info("Extracting attention weights...")
        with torch.no_grad():
            _ = classifier(features)

        # Get attention weights
        attention_weights = extractor.get_weights()  # [B, Q, N]
        if attention_weights is None:
            logger.error("Failed to extract attention weights!")
            break

        logger.info(f"Attention weights shape: {attention_weights.shape}")

        # Process attention weights
        # Use the effective temporal length inferred from the encoder output. This
        # handles encoders that concatenate multiple clips/views.
        T = T_effective

        # Reshape to grid
        attention_grid = reshape_attention_to_grid(attention_weights, T, H_patch, W_patch)
        logger.info(f"Attention grid shape: {attention_grid.shape}")

        # Normalize with robust quantiles after aggregation/debiasing.
        attention_grid = normalize_attention(attention_grid, low_quantile=norm_low_q, high_quantile=norm_high_q)

        # Extract frames from the selected sample for visualization.
        video_frames = extract_video_frames_from_sample(
            sample_clips,
            DEFAULT_NORMALIZATION[0],
            DEFAULT_NORMALIZATION[1],
        )
        logger.info(f"Extracted {len(video_frames)} video frames")

        # Temporal mismatch must be explicit; avoid trilinear interpolation artifacts over time.
        T_actual = len(video_frames)
        if T_actual != T:
            logger.warning(
                f"Temporal mismatch: encoder inferred T_effective={T} but extracted {T_actual} actual video frames. "
                "Will only align if ratio is integer (repeat or average), otherwise this is a pipeline inconsistency."
            )
            T = T_actual

        # Upsample to the actual extracted video resolution.
        frame_h, frame_w = video_frames[0].shape[:2]
        attention_up = upsample_attention_to_video_resolution(
            attention_grid,
            target_shape=(T, frame_h, frame_w),
        )
        logger.info(f"Upsampled attention shape: {attention_up.shape}")

        # Create attention sequence [T, H, W]
        attention_seq = attention_up.squeeze(0).squeeze(0)  # Remove batch and channel dims

        # Create output video
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        output_video = output_dir / f"attention_sample_{sample_index:04d}.mp4"

        create_attention_video(
            video_frames,
            attention_seq,
            str(output_video),
            fps=fps,
            alpha=heatmap_alpha,
            threshold=threshold,
        )

        # Also create a diagnostic plot showing attention heatmap for middle frame
        logger.info("Creating diagnostic plots...")
        middle_frame_idx = T // 2
        fig, axes = plt.subplots(1, 3, figsize=(15, 5))

        # Original frame
        axes[0].imshow(video_frames[middle_frame_idx])
        axes[0].set_title(f"Original Frame (t={middle_frame_idx})")
        axes[0].axis('off')

        # Attention heatmap
        attn_frame = attention_seq[middle_frame_idx].detach().cpu().numpy()
        im = axes[1].imshow(attn_frame, cmap='jet')
        axes[1].set_title(f"Attention Heatmap (t={middle_frame_idx})")
        axes[1].axis('off')
        plt.colorbar(im, ax=axes[1])

        # Blended
        heatmap_uint8 = attention_to_heatmap(attn_frame, vmin=args.threshold)
        blended = blend_heatmap_with_frame(
            video_frames[middle_frame_idx],
            heatmap_uint8,
            attention_frame=attn_frame,
            alpha=0.5,
            threshold=threshold,
        )
        axes[2].imshow(blended)
        axes[2].set_title(f"Blended (α={0.5})")
        axes[2].axis('off')

        plt.tight_layout()
        plot_path = output_dir / f"attention_sample_{sample_index:04d}_diagnostic.png"
        plt.savefig(plot_path, dpi=150, bbox_inches='tight')
        logger.info(f"Saved diagnostic plot to {plot_path}")
        plt.close()

        break

    if not sample_found:
        logger.error(f"Sample {sample_index} not found in test set (only {batch_idx + 1} batches)")

    # Cleanup
    extractor.remove_hook()
    logger.info("✓ Attention visualization complete!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Visualize spatial attention weights from attentive probes"
    )
    parser.add_argument(
        "--eval_config",
        required=True,
        help="Path to evaluation config YAML file",
    )
    parser.add_argument(
        "--probe_checkpoint",
        required=True,
        help="Path to trained probe checkpoint (.pt file)",
    )
    parser.add_argument(
        "--test_data_path",
        help="Path to test data CSV (default: uses val path from config)",
    )
    parser.add_argument(
        "--output_dir",
        default="notebooks/attention_visualizations",
        help="Directory to save attention videos and plots",
    )
    parser.add_argument(
        "--sample_index",
        type=int,
        default=0,
        help="Which sample in test set to visualize",
    )
    parser.add_argument(
        "--gpu_id",
        type=int,
        default=0,
        help="GPU ID to use",
    )
    parser.add_argument(
        "--heatmap_alpha",
        type=float,
        default=0.5,
        help="Heatmap blending coefficient (0=original frame only, 1=heatmap only)",
    )
    parser.add_argument(
        "--fps",
        type=int,
        default=10,
        help="Output video frame rate",
    )
    parser.add_argument('--head_idx', type=int, default=None)
    parser.add_argument(
        "--head_aggregation",
        type=str,
        default="entropy_weighted",
        choices=["mean", "max", "entropy_weighted"],
        help="How to aggregate cross-attention heads into one map",
    )
    parser.add_argument(
        "--disable_uniform_debias",
        action="store_true",
        help="Disable subtraction of the uniform 1/N attention floor before normalization",
    )
    parser.add_argument(
        "--norm_low_q",
        type=float,
        default=0.01,
        help="Lower quantile used for robust normalization",
    )
    parser.add_argument(
        "--norm_high_q",
        type=float,
        default=0.99,
        help="Upper quantile used for robust normalization",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.0,
        help="Optional visualization threshold; 0.0 shows all attention values",
    )

    args = parser.parse_args()

    visualize_attention(
        eval_config_path=args.eval_config,
        probe_checkpoint_path=args.probe_checkpoint,
        test_data_path=args.test_data_path,
        output_dir=args.output_dir,
        sample_index=args.sample_index,
        gpu_id=args.gpu_id,
        heatmap_alpha=args.heatmap_alpha,
        fps=args.fps,
        head_idx=args.head_idx,
        threshold=args.threshold,
        head_aggregation=args.head_aggregation,
        debias_uniform=not args.disable_uniform_debias,
        norm_low_q=args.norm_low_q,
        norm_high_q=args.norm_high_q,
    )

